
2018-12-08 11:49:53,030 - error - INFO - basic_log : 19 - Traceback (most recent call last):
  File "/home/work/erp/erp_sites/views/commodity.py", line 251, in singleCommoditySelect
    commoditySpecicicationID = request.GET['commoditySpecicicationID']
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.13-py2.7.egg/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'commoditySpecicicationID'"

